name: Build ESP8266 Bin
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/

      - name: Setup ESP8266 Core
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266

      - name: Install Libraries
        run: |
          arduino-cli lib install "ESPAsyncWebServer"
          arduino-cli lib install "ESPAsyncTCP"

      - name: Compile Code
        run: |
          mkdir build
          arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 --output-dir ./build .

      - name: Upload .bin File
        uses: actions/upload-artifact@v4
        with:
          name: firmware-binary
          path: ./build/*.bin
          
